---
# tasks file for apache
    - name: Update All Packages
      yum:
        name: '*'
        state: latest
    - name: Install Apache
      yum: 
        name: httpd
        state: installed

    - name:  apache url
      shell: echo "Hello from the Ansible" > /var/www/html/index.html
      args:
         executable: /bin/bash 
      notify:
        - Reload Apache
     
    - name: public IP
      shell: 
        # cmd: curl http://169.254.169.254/latest/meta-data/public-ipv4
        cmd: /usr/bin/ec2-metadata | grep public-ipv4
      register: curl
    - debug: var=curl.stdout_lines
