download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/geerlingguy-k8s-0.10.0.tar.gz
format_version: 1.0.0
name: k8s
namespace: geerlingguy
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.10.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/geerlingguy/k8s/versions/0.10.0/
